baseURL = "/"
languageCode = "en-us"
title = "Jason Madigan"
theme = "m10c"

[params]
description = "He's just zis guy, ya know?"
author = "Jason Madigan"
avatar = "0.jpg"

[[params.social]]
  name = "github"
  url = "https://github.com/jasonmadigan"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/jasonmadigan"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"

[markup.goldmark.renderer]
  unsafe = true